name: Build Docs Content

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Deploy to GitHub Pages
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          npm install
          npm run docs:build
          cp docs/.vitepress/cp-rename.sh docs/.vitepress/dist/releases/cp-rename.sh
          cd docs/.vitepress/dist/releases
          chmod +x ./cp-rename.sh
          ./cp-rename.sh
          ls -l
          cd ../../../..
          cd docs/.vitepress/dist
          git init
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m 'deploy'2
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/.vitepress/dist
